//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoJohns.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public string ClientId { get; set; }
        public string Comment1 { get; set; }
        public bool ClientType { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
