//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoJohns.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NoJohnsModelContainer : DbContext
    {
        public NoJohnsModelContainer()
            : base("name=NoJohnsModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> ClientsSet { get; set; }
        public virtual DbSet<Comments> CommentsSet { get; set; }
        public virtual DbSet<Types> TypesSet { get; set; }
        public virtual DbSet<Procedures> ProceduresSet { get; set; }
        public virtual DbSet<ClientsProcedures> ClientsProceduresSet { get; set; }
    }
}
