//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoJohns.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedure
    {
        public int Id { get; set; }
        public string Comment { get; set; }
        public int TypeId { get; set; }
        public decimal Price { get; set; }
        public string Status { get; set; }
    
        public virtual ClientsProcedure ClientsProcedure { get; set; }
        public virtual ProcedureType ProcedureType { get; set; }
    }
}
