//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoJohns.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsProcedures
    {
        public string ClientId { get; set; }
        public int ProcedureId { get; set; }
        public bool ClientType { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Procedure Procedure { get; set; }
    }
}
