#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tramites.Resource", IsApplication=true)]

namespace Tramites
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int Login = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int Logo = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int Pass = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int SignUpButton = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int User = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int button1 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int pAddress = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int pMail = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int pPhone = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int plName = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int progressBar = 2131034123;
			
			// aapt resource value: 0x7f050011
			public const int sAddress = 2131034129;
			
			// aapt resource value: 0x7f05000e
			public const int sMail = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int sPassword = 2131034125;
			
			// aapt resource value: 0x7f050012
			public const int sPhone = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int sSignUpButton = 2131034131;
			
			// aapt resource value: 0x7f05000c
			public const int sUsername = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int sfName = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int slName = 2131034128;
			
			// aapt resource value: 0x7f050000
			public const int text1 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Comments = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Dialog_editProfile = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Profile = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SignUp = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int action_compose = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int action_search = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
