#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tramites.Resource", IsApplication=true)]

namespace Tramites
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int Login = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int Logo = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int Pass = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int SignUpButton = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int User = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int button1 = 2131099654;
			
			// aapt resource value: 0x7f060014
			public const int editProfile = 2131099668;
			
			// aapt resource value: 0x7f060008
			public const int pAddress = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int pMail = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int pPhone = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int plName = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int progressBar = 2131099659;
			
			// aapt resource value: 0x7f060011
			public const int sAddress = 2131099665;
			
			// aapt resource value: 0x7f06000e
			public const int sMail = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int sPassword = 2131099661;
			
			// aapt resource value: 0x7f060012
			public const int sPhone = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int sSignUpButton = 2131099667;
			
			// aapt resource value: 0x7f06000c
			public const int sUsername = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int sfName = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int slName = 2131099664;
			
			// aapt resource value: 0x7f060000
			public const int text1 = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Comments = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Dialog_editProfile = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Profile = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SignUp = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int mymenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int action_compose = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int action_search = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
