//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoJohns.Portable
{
    using System;
    using System.Collections.Generic;
    
    public class Comments
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string AuthorUser { get; set; }
        public string Comment { get; set; }
        public bool ClientType { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
