//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoJohns.Portable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedures
    {
        public Procedures()
        {
            this.ClientsProcedures = new HashSet<ClientsProcedures>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int TypesId { get; set; }
        public decimal Price { get; set; }
        public string Status { get; set; }
    
        public virtual Types Types { get; set; }
        public virtual ICollection<ClientsProcedures> ClientsProcedures { get; set; }
    }
}
