//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoJohns.Portable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Types
    {
        public Types()
        {
            this.Procedures = new HashSet<Procedures>();
        }
    
        public int Id { get; set; }
        public string ProcedureName { get; set; }
    
        public virtual ICollection<Procedures> Procedures { get; set; }
    }
}
