//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoJohns.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NoJohnsModelContainer : DbContext
    {
        public NoJohnsModelContainer()
            : base("name=NoJohnsModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> ClientsSet { get; set; }
        public virtual DbSet<Comments> CommentsSet { get; set; }
        public virtual DbSet<Types> TypesSet { get; set; }
        public virtual DbSet<Procedures> ProceduresSet { get; set; }
        public virtual DbSet<ClientsProcedures> ClientsProceduresSet { get; set; }
    
        public virtual int Search_Username(string usuario_In, ObjectParameter id)
        {
            var usuario_InParameter = usuario_In != null ?
                new ObjectParameter("Usuario_In", usuario_In) :
                new ObjectParameter("Usuario_In", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Search_Username", usuario_InParameter, id);
        }
    
        public virtual ObjectResult<Nullable<int>> GetByUsername(string usuario_In, ObjectParameter id)
        {
            var usuario_InParameter = usuario_In != null ?
                new ObjectParameter("Usuario_In", usuario_In) :
                new ObjectParameter("Usuario_In", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetByUsername", usuario_InParameter, id);
        }
    }
}
